export const data = [
  {
    id: 1,
    imgURL: "https://i.ibb.co/HKtpBKH/masum.jpg",
    name: "Tahidul Islam Masum",
    designation: "Directing Manager",
    description: "Some text about the career....",
    facebook: "#",
    github: "#",
    linkedIn: "#",
  },
  {
    id: 2,
    imgURL: "https://i.ibb.co/W2vtSF0/rasel.jpg",
    name: "Rasel Ahmed",
    designation: "Adviser",
    description: "Some text about the career....",
    facebook: "https://www.facebook.com/rasalahmad.ahmad.3/",
    github: "https://github.com/Rasalahmad/",
    linkedIn: "https://www.linkedin.com/in/ahmad-rasal/",
  },
  {
    id: 3,
    imgURL: "https://i.ibb.co/9ssTSq7/Shahin.jpg",
    name: "Yeasin arfat shahin",
    designation: "CEO",
    description: "Some text about the career....",
    facebook: "#",
    github: "#",
    linkedIn: "#",
  },
  {
    id: 4,
    imgURL: "https://i.ibb.co/gJmbQS0/uhai.jpg",
    name: "UHai Mong",
    designation: "Developer",
    description: "Some text about the career....",
    facebook: "https://facebook.com/uhaising.marma",
    github: "https://github.com/UhaiMong",
    linkedIn: "https://linkedin.com/uhaimong/b344",
  },
  {
    id: 5,
    imgURL: "https://i.ibb.co/WkZxYdn/dawsing.jpg",
    name: "Dawsing",
    designation: "Product Manager",
    description: "Some text about the career....",
    facebook: "https://www.facebook.com/swaypai.rowock/",
    github: "#",
    linkedIn: "https://www.linkedin.com/in/dawsing-marma-6b6b001b6",
  },
  {
    id: 6,
    imgURL: "https://i.ibb.co/s1nTTSR/talimul.jpg",
    name: "Talimul Islam",
    designation: "Developer",
    description: "Some text about the career....",
    facebook: "https://www.facebook.com/talimul.islam.52493",
    github: "https://github.com/Talimul212",
    linkedIn: "https://www.linkedin.com/in/talimul-islam-77965a22a/",
  },
  {
    id: 11,
    imgURL: "https://i.ibb.co/5G13WmF/Image-Tanvirul-Islam.jpg",
    name: "Tanvir Islam",
    designation: "UI/UX Designer",
    description: "Some text about the career....",
    facebook: "https://www.facebook.com/imtanvirus",
    github: "#",
    linkedIn: "https://www.linkedin.com/in/tanvir-islam-890a611a5",
  },
  {
    id: 8,
    imgURL: "https://i.ibb.co/hg5YP2S/Ranghin-Mro.jpg",
    name: "Ranghin",
    designation: "Public Relation Officer",
    description: "Some text about the career....",
    facebook: "https://web.facebook.com/rang.hin.92",
    github: "https://github.com/ranghin15",
    linkedIn: "http://linkedin.com/in/ranghinmro",
  },
  {
    id: 7,
    imgURL: "https://i.ibb.co/tQTBLRB/umay2.jpg",
    name: "Umay Fru",
    designation: "Logistic Supporter",
    description: "Some text about the career....",
    facebook: "#",
    github: "#",
    linkedIn: "#",
  },
  {
    id: 8,
    imgURL: "https://i.ibb.co/2MRC8pm/jerin.jpg",
    name: "Jerin",
    designation: "Human Resource Officer",
    description: "Some text about the career....",
    facebook: "#",
    github: "#",
    linkedIn: "#",
  },
  {
    id: 9,
    imgURL: "https://i.ibb.co/zJrsHw0/saksin.jpg",
    name: "Saksin Mro",
    designation: "Back-end Developer",
    description: "Some text about the career....",
    facebook: "https://www.facebook.com/Engi.saksingmro?mibextid=ZbWKwL",
    github: "#",
    linkedIn: "https://www.linkedin.com/in/saksing-mro-b07007276",
  },
  {
    id: 10,
    imgURL: "https://i.ibb.co/5BZvb4s/sadia.jpg",
    name: "Riya",
    designation: "Designer",
    description: "Some text about the career....",
    facebook: "#",
    github: "#",
    linkedIn: "#",
  },
  {
    id: 11,
    imgURL: "https://i.ibb.co/P9mjGDZ/tonmoy.jpg",
    name: "Tonmoy",
    designation: "Human Resource Officer",
    description: "Some text about the career....",
    facebook: "#",
    github: "#",
    linkedIn: "#",
  },
];
