export const productData = [
  {
    id: 1,
    name: "T.I Masum",
    designation: "Dev",
    imgURL: "https://i.ibb.co/HKtpBKH/masum.jpg",
    faceBook: "",
    gitHub: "",
    linkedIn: "",
  },
  {
    id: 2,
    name: "Rasel Ahmed",
    designation: "Dev",
    imgURL: "https://i.ibb.co/W2vtSF0/rasel.jpg",
    faceBook: "",
    gitHub: "",
    linkedIn: "",
  },
  {
    id: 3,
    name: "Shahin",
    designation: "Dev",
    imgURL: "https://i.ibb.co/HKtpBKH/masum.jpg",
    faceBook: "",
    gitHub: "",
    linkedIn: "",
  },
  {
    id: 4,
    name: "Uhai",
    designation: "Dev",
    imgURL: "https://i.ibb.co/gJmbQS0/uhai.jpg",
    faceBook: "",
    gitHub: "",
    linkedIn: "",
  },
  {
    id: 5,
    name: "Dawsing",
    designation: "Dev",
    imgURL: "https://i.ibb.co/WkZxYdn/dawsing.jpg",
    faceBook: "",
    gitHub: "",
    linkedIn: "",
  },
  {
    id: 6,
    name: "Talimul",
    designation: "Dev",
    imgURL: "https://i.ibb.co/s1nTTSR/talimul.jpg",
    faceBook: "",
    gitHub: "",
    linkedIn: "",
  },
  {
    id: 7,
    name: "Umay",
    designation: "Dev",
    imgURL: "https://i.ibb.co/pJGHM13/umay.jpg",
    faceBook: "",
    gitHub: "",
    linkedIn: "",
  },
  {
    id: 8,
    name: "Jerin",
    designation: "Dev",
    imgURL: "https://i.ibb.co/2MRC8pm/jerin.jpg",
    faceBook: "",
    gitHub: "",
    linkedIn: "",
  },
  {
    id: 9,
    name: "Saksin",
    designation: "Dev",
    imgURL: "https://i.ibb.co/zJrsHw0/saksin.jpg",
    faceBook: "",
    gitHub: "",
    linkedIn: "",
  },
  {
    id: 10,
    name: "Sadiya",
    designation: "Dev",
    imgURL: "https://i.ibb.co/5BZvb4s/sadia.jpg",
    faceBook: "",
    gitHub: "",
    linkedIn: "",
  },
];

