export const portfolioData = [
  // {
  //   id: 1,
  //   title: "Food Finder",
  //   projectType: "web-app",
  //   imgURL: "https://i.ibb.co/mHxW1w3/web-dev-resized.png",
  //   description: "This is the first project description.",
  //   projectLink: "https://example.com/project1",
  // },
  // {
  //   id: 2,
  //   title: "E-Commerce",
  //   projectType: "e-commerce",
  //   imgURL: "https://i.ibb.co/KGpRmcC/desktop.jpg",
  //   description: "This is the second project description.",
  //   projectLink: "https://example.com/project2",
  // },
  {
    id: 3,
    title: "Product Resale Services",
    projectType: "web-app",
    imgURL: "https://i.ibb.co/w6R2M1k/Home-Page-T.png",
    description: "This is the third project description.",
    projectLink: "https://flourishing-gecko-8cb030.netlify.app",
  },
  {
    id: 4,
    title: "CHT Travel",
    projectType: "web-app",
    imgURL: "https://i.ibb.co/gJntZFq/Slide1.png",
    description: "This is the third project description.",
    projectLink: "https://cht.hilltractstech.com/",
  },
  {
    id: 5,
    title: "Green Land Resort",
    projectType: "web-app",
    imgURL: "https://i.ibb.co/89f80xJ/Home-Page-R.png",
    description: "Green Land hotel and resturant web",
    projectLink: "https://bban.hotelgreenlandbd.com",
  },
];
