export const portfolioData = [
  {
    id: 1,
    title: "Food Finder",
    projectType: "web-app",
    imgURL: "https://i.ibb.co/mHxW1w3/web-dev-resized.png",
    description: "This is the first project description.",
    projectLink: "https://example.com/project1",
  },
  {
    id: 2,
    title: "E-Commerce",
    projectType: "e-commerce",
    imgURL: "https://i.ibb.co/KGpRmcC/desktop.jpg",
    description: "This is the second project description.",
    projectLink: "https://example.com/project2",
  },
  {
    id: 3,
    title: "CHT Travel",
    projectType: "web-app",
    imgURL: "https://i.ibb.co/PxGFVFK/news.jpg",
    description: "This is the third project description.",
    projectLink: "https://example.com/project3",
  },
  {
    id: 4,
    title: "Cyber Hack",
    projectType: "security",
    imgURL: "https://i.ibb.co/PxGFVFK/news.jpg",
    description: "This is the third project description.",
    projectLink: "https://example.com/project3",
  },
  {
    id: 5,
    title: "Green Land Resort",
    projectType: "web-app",
    imgURL: "https://i.ibb.co/PxGFVFK/news.jpg",
    description: "Green Land hotel and resturant web",
    projectLink: "https://bban.hotelgreenlandbd.com",
  },
];
